version: '3.1'

services:
    backend:
      build: ./backend
      environment:
        - PORT=8000
      restart: unless-stopped
      ports: 
       - "8000:8000"

    frontend:
      build: ./frontend
      environment:
       - PORT=3000
      ports:
       - "3000:3000"
